version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: medical-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medical_events
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingest-service:
    build:
      context: ./services/ingest-service
      dockerfile: Dockerfile
    container_name: ingest-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/medical_events
      PROCESSOR_URL: http://processor-service:3001
    depends_on:
      mongodb:
        condition: service_healthy
      processor-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  processor-service:
    build:
      context: ./services/processor-service
      dockerfile: Dockerfile
    container_name: processor-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongodb:27017/medical_events
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
    driver: local

